/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.0 Component Pack 2
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <PinLedAlarm_aliases.h>
#include <PinLedAlarm.h>
#include <PinLedMotorOn_aliases.h>
#include <PinLedMotorOn.h>
#include <PinLedInRange_aliases.h>
#include <PinLedInRange.h>
#include <PinLedRemoteBattLevelHigh_aliases.h>
#include <PinLedRemoteBattLevelHigh.h>
#include <PinLedRemoteBattLevelMed_aliases.h>
#include <PinLedRemoteBattLevelMed.h>
#include <PinLedRemoteBattLevelLow_aliases.h>
#include <PinLedRemoteBattLevelLow.h>
#include <PinLedBoardBattLevelHigh_aliases.h>
#include <PinLedBoardBattLevelHigh.h>
#include <PinLedBoardBattLevelMed_aliases.h>
#include <PinLedBoardBattLevelMed.h>
#include <PinLedBoardBattLevelLow_aliases.h>
#include <PinLedBoardBattLevelLow.h>
#include <CapSense.h>
#include <CapSense_CSHL.h>
#include <CapSense_Pins.h>
#include <CapSense_TunerHelper.h>
#include <UartXbee.h>
#include <PinXbeeIsSleep_aliases.h>
#include <PinXbeeIsSleep.h>
#include <AdcSar.h>
#include <AMuxAdc.h>
#include <UartDebug.h>
#include <PinDebug_aliases.h>
#include <PinDebug.h>
#include <TimerMainTick.h>
#include <IsrMainTick.h>
#include <PinXbeeSleep_aliases.h>
#include <PinXbeeSleep.h>
#include <CapSense_CompCH0.h>
#include <CapSense_AMuxCH0.h>
#include <CapSense_IntClock.h>
#include <AdcSar_theACLK.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
