<?xml version="1.0" encoding="utf-8"?>
<CyXmlSerializer>
<!--This file is machine generated and read. It is not intended to be edited by hand.-->
<!--Due to this, there is no schema for this file.-->
<CyGuid_7a7929f8-5e3b-4f86-a093-2d4ee6513111 type_name="CyDesigner.Common.ProjMgmt.Model.CyPrjMgmtProjectCustomData" version="1">
<CyGuid_fdba8dfd-b15b-4469-9bbb-9e40c3e70997 type_name="CyDesigner.Common.Base.CyCustomData" version="2">
<userData>
<dataGuid v="47ec7058-2f43-4a2f-ae73-172624e235df">
<CyGuid_47ec7058-2f43-4a2f-ae73-172624e235df type_name="CyDesigner.Common.ProjMgmt.Model.CyConfDepList" version="1">
<boot_component v="cy_boot_v2_40" />
<name v="cmpl_deps">
<CyGuid_f44455c5-3770-4452-b988-0a7a7ff46256 type_name="CyDesigner.Common.ProjMgmt.Model.CyConfigDependencies" version="1">
<dependency_info name="c9323d49-d323-40b8-9b59-cc008d68a989@Debug@CortexM3" xml_contents_version="2">
<CyGuid_1173175f-1b9b-4ad4-a065-754a48a27021 type_name="CyDesigner.Common.Base.CyFileDeps" version="1">
<file name=".\CortexM3\ARM_GCC_441\Debug\Adc.o">
<dep name=".\Generated_Source\PSoC5\AdcSar.h" />
<dep name=".\Generated_Source\PSoC5\AdcSar_theACLK.h" />
<dep name=".\Generated_Source\PSoC5\CYDEVICE_TRM.H" />
<dep name=".\Generated_Source\PSoC5\CYFITTER.H" />
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\ClockPwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\CyDmac.h" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\CySpc.h" />
<dep name=".\Generated_Source\PSoC5\IsrMainTick.h" />
<dep name=".\Generated_Source\PSoC5\IsrMotionSensor.h" />
<dep name=".\Generated_Source\PSoC5\PinLedGreen.h" />
<dep name=".\Generated_Source\PSoC5\PinLedGreen_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLedOrange.h" />
<dep name=".\Generated_Source\PSoC5\PinLedOrange_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLedRed.h" />
<dep name=".\Generated_Source\PSoC5\PinLedRed_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFront.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFront_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightRear.h" />
<dep name=".\Generated_Source\PSoC5\PinLightRear_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightSkirting.h" />
<dep name=".\Generated_Source\PSoC5\PinLightSkirting_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinMotionSensor.h" />
<dep name=".\Generated_Source\PSoC5\PinMotionSensor_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmMotor.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmMotor_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmPiezo_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinXbeeSleep.h" />
<dep name=".\Generated_Source\PSoC5\PinXbeeSleep_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PwmMotor.h" />
<dep name=".\Generated_Source\PSoC5\PwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\TimerMainTick.h" />
<dep name=".\Generated_Source\PSoC5\UartDebug.h" />
<dep name=".\Generated_Source\PSoC5\UartXbee.h" />
<dep name=".\Generated_Source\PSoC5\core_cm3.h" />
<dep name=".\Generated_Source\PSoC5\core_cm3_psoc5.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter_cfg.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\project.h" />
<dep name=".\Adc.c" />
<dep name=".\Adc.h" />
<dep name=".\Config.h" />
<dep name=".\device.h" />
<dep name="..\common\PublicObjects.h" />
</file>
<file name=".\Generated_Source\PSoC5\AdcSar.h" />
<file name=".\Generated_Source\PSoC5\AdcSar_theACLK.h" />
<file name=".\Generated_Source\PSoC5\CYDEVICE_TRM.H" />
<file name=".\Generated_Source\PSoC5\CYFITTER.H" />
<file name=".\Generated_Source\PSoC5\CYLIB.H" />
<file name=".\Generated_Source\PSoC5\CYSPC.H" />
<file name=".\Generated_Source\PSoC5\CYTYPES.H" />
<file name=".\Generated_Source\PSoC5\ClockPwmPiezo.h" />
<file name=".\Generated_Source\PSoC5\CyDmac.h" />
<file name=".\Generated_Source\PSoC5\CyFlash.h" />
<file name=".\Generated_Source\PSoC5\CyLib.h" />
<file name=".\Generated_Source\PSoC5\CySpc.h" />
<file name=".\Generated_Source\PSoC5\IsrMainTick.h" />
<file name=".\Generated_Source\PSoC5\IsrMotionSensor.h" />
<file name=".\Generated_Source\PSoC5\PinLedGreen.h" />
<file name=".\Generated_Source\PSoC5\PinLedGreen_aliases.h" />
<file name=".\Generated_Source\PSoC5\PinLedOrange.h" />
<file name=".\Generated_Source\PSoC5\PinLedOrange_aliases.h" />
<file name=".\Generated_Source\PSoC5\PinLedRed.h" />
<file name=".\Generated_Source\PSoC5\PinLedRed_aliases.h" />
<file name=".\Generated_Source\PSoC5\PinLightFront.h" />
<file name=".\Generated_Source\PSoC5\PinLightFront_aliases.h" />
<file name=".\Generated_Source\PSoC5\PinLightRear.h" />
<file name=".\Generated_Source\PSoC5\PinLightRear_aliases.h" />
<file name=".\Generated_Source\PSoC5\PinLightSkirting.h" />
<file name=".\Generated_Source\PSoC5\PinLightSkirting_aliases.h" />
<file name=".\Generated_Source\PSoC5\PinMotionSensor.h" />
<file name=".\Generated_Source\PSoC5\PinMotionSensor_aliases.h" />
<file name=".\Generated_Source\PSoC5\PinPwmMotor.h" />
<file name=".\Generated_Source\PSoC5\PinPwmMotor_aliases.h" />
<file name=".\Generated_Source\PSoC5\PinPwmPiezo.h" />
<file name=".\Generated_Source\PSoC5\PinPwmPiezo_aliases.h" />
<file name=".\Generated_Source\PSoC5\PinXbeeSleep.h" />
<file name=".\Generated_Source\PSoC5\PinXbeeSleep_aliases.h" />
<file name=".\Generated_Source\PSoC5\PwmMotor.h" />
<file name=".\Generated_Source\PSoC5\PwmPiezo.h" />
<file name=".\Generated_Source\PSoC5\TimerMainTick.h" />
<file name=".\Generated_Source\PSoC5\UartDebug.h" />
<file name=".\Generated_Source\PSoC5\UartXbee.h" />
<file name=".\Generated_Source\PSoC5\core_cm3.h" />
<file name=".\Generated_Source\PSoC5\core_cm3_psoc5.h" />
<file name=".\Generated_Source\PSoC5\cyPm.h" />
<file name=".\Generated_Source\PSoC5\cydevice.h" />
<file name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<file name=".\Generated_Source\PSoC5\cyfitter.h" />
<file name=".\Generated_Source\PSoC5\cyfitter_cfg.h" />
<file name=".\Generated_Source\PSoC5\cypins.h" />
<file name=".\Generated_Source\PSoC5\cytypes.h" />
<file name=".\Generated_Source\PSoC5\project.h" />
<file name=".\Adc.c" />
<file name=".\Adc.h" />
<file name=".\Config.h" />
<file name=".\device.h" />
<file name="..\common\PublicObjects.h" />
<file name=".\CortexM3\ARM_GCC_441\Debug\Comms.o">
<dep name=".\Generated_Source\PSoC5\AdcSar.h" />
<dep name=".\Generated_Source\PSoC5\AdcSar_theACLK.h" />
<dep name=".\Generated_Source\PSoC5\CYDEVICE_TRM.H" />
<dep name=".\Generated_Source\PSoC5\CYFITTER.H" />
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\ClockPwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\CyDmac.h" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\CySpc.h" />
<dep name=".\Generated_Source\PSoC5\IsrMainTick.h" />
<dep name=".\Generated_Source\PSoC5\IsrMotionSensor.h" />
<dep name=".\Generated_Source\PSoC5\PinLedGreen.h" />
<dep name=".\Generated_Source\PSoC5\PinLedGreen_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLedOrange.h" />
<dep name=".\Generated_Source\PSoC5\PinLedOrange_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLedRed.h" />
<dep name=".\Generated_Source\PSoC5\PinLedRed_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFront.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFront_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightRear.h" />
<dep name=".\Generated_Source\PSoC5\PinLightRear_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightSkirting.h" />
<dep name=".\Generated_Source\PSoC5\PinLightSkirting_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinMotionSensor.h" />
<dep name=".\Generated_Source\PSoC5\PinMotionSensor_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmMotor.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmMotor_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmPiezo_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinXbeeSleep.h" />
<dep name=".\Generated_Source\PSoC5\PinXbeeSleep_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PwmMotor.h" />
<dep name=".\Generated_Source\PSoC5\PwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\TimerMainTick.h" />
<dep name=".\Generated_Source\PSoC5\UartDebug.h" />
<dep name=".\Generated_Source\PSoC5\UartXbee.h" />
<dep name=".\Generated_Source\PSoC5\core_cm3.h" />
<dep name=".\Generated_Source\PSoC5\core_cm3_psoc5.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter_cfg.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\project.h" />
<dep name=".\Comms.c" />
<dep name=".\Comms.h" />
<dep name=".\Config.h" />
<dep name=".\device.h" />
<dep name="..\common\PublicObjects.h" />
</file>
<file name=".\Comms.c" />
<file name=".\Comms.h" />
<file name=".\CortexM3\ARM_GCC_441\Debug\Led.o">
<dep name=".\Generated_Source\PSoC5\AdcSar.h" />
<dep name=".\Generated_Source\PSoC5\AdcSar_theACLK.h" />
<dep name=".\Generated_Source\PSoC5\CYDEVICE_TRM.H" />
<dep name=".\Generated_Source\PSoC5\CYFITTER.H" />
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\ClockPwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\CyDmac.h" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\CySpc.h" />
<dep name=".\Generated_Source\PSoC5\IsrMainTick.h" />
<dep name=".\Generated_Source\PSoC5\IsrMotionSensor.h" />
<dep name=".\Generated_Source\PSoC5\PinLedGreen.h" />
<dep name=".\Generated_Source\PSoC5\PinLedGreen_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLedOrange.h" />
<dep name=".\Generated_Source\PSoC5\PinLedOrange_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLedRed.h" />
<dep name=".\Generated_Source\PSoC5\PinLedRed_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFront.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFront_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightRear.h" />
<dep name=".\Generated_Source\PSoC5\PinLightRear_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightSkirting.h" />
<dep name=".\Generated_Source\PSoC5\PinLightSkirting_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinMotionSensor.h" />
<dep name=".\Generated_Source\PSoC5\PinMotionSensor_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmMotor.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmMotor_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmPiezo_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinXbeeSleep.h" />
<dep name=".\Generated_Source\PSoC5\PinXbeeSleep_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PwmMotor.h" />
<dep name=".\Generated_Source\PSoC5\PwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\TimerMainTick.h" />
<dep name=".\Generated_Source\PSoC5\UartDebug.h" />
<dep name=".\Generated_Source\PSoC5\UartXbee.h" />
<dep name=".\Generated_Source\PSoC5\core_cm3.h" />
<dep name=".\Generated_Source\PSoC5\core_cm3_psoc5.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter_cfg.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\project.h" />
<dep name=".\Config.h" />
<dep name=".\Led.c" />
<dep name=".\Led.h" />
<dep name=".\device.h" />
</file>
<file name=".\Led.c" />
<file name=".\Led.h" />
<file name=".\CortexM3\ARM_GCC_441\Debug\Lights.o">
<dep name=".\Generated_Source\PSoC5\AdcSar.h" />
<dep name=".\Generated_Source\PSoC5\AdcSar_theACLK.h" />
<dep name=".\Generated_Source\PSoC5\CYDEVICE_TRM.H" />
<dep name=".\Generated_Source\PSoC5\CYFITTER.H" />
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\ClockPwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\CyDmac.h" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\CySpc.h" />
<dep name=".\Generated_Source\PSoC5\IsrMainTick.h" />
<dep name=".\Generated_Source\PSoC5\IsrMotionSensor.h" />
<dep name=".\Generated_Source\PSoC5\PinLedGreen.h" />
<dep name=".\Generated_Source\PSoC5\PinLedGreen_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLedOrange.h" />
<dep name=".\Generated_Source\PSoC5\PinLedOrange_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLedRed.h" />
<dep name=".\Generated_Source\PSoC5\PinLedRed_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFront.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFront_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightRear.h" />
<dep name=".\Generated_Source\PSoC5\PinLightRear_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightSkirting.h" />
<dep name=".\Generated_Source\PSoC5\PinLightSkirting_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinMotionSensor.h" />
<dep name=".\Generated_Source\PSoC5\PinMotionSensor_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmMotor.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmMotor_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmPiezo_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinXbeeSleep.h" />
<dep name=".\Generated_Source\PSoC5\PinXbeeSleep_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PwmMotor.h" />
<dep name=".\Generated_Source\PSoC5\PwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\TimerMainTick.h" />
<dep name=".\Generated_Source\PSoC5\UartDebug.h" />
<dep name=".\Generated_Source\PSoC5\UartXbee.h" />
<dep name=".\Generated_Source\PSoC5\core_cm3.h" />
<dep name=".\Generated_Source\PSoC5\core_cm3_psoc5.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter_cfg.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\project.h" />
<dep name=".\Config.h" />
<dep name=".\Lights.c" />
<dep name=".\Lights.h" />
<dep name=".\device.h" />
<dep name="..\common\PublicObjects.h" />
</file>
<file name=".\Lights.c" />
<file name=".\Lights.h" />
<file name=".\CortexM3\ARM_GCC_441\Debug\Motor.o">
<dep name=".\Generated_Source\PSoC5\AdcSar.h" />
<dep name=".\Generated_Source\PSoC5\AdcSar_theACLK.h" />
<dep name=".\Generated_Source\PSoC5\CYDEVICE_TRM.H" />
<dep name=".\Generated_Source\PSoC5\CYFITTER.H" />
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\ClockPwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\CyDmac.h" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\CySpc.h" />
<dep name=".\Generated_Source\PSoC5\IsrMainTick.h" />
<dep name=".\Generated_Source\PSoC5\IsrMotionSensor.h" />
<dep name=".\Generated_Source\PSoC5\PinLedGreen.h" />
<dep name=".\Generated_Source\PSoC5\PinLedGreen_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLedOrange.h" />
<dep name=".\Generated_Source\PSoC5\PinLedOrange_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLedRed.h" />
<dep name=".\Generated_Source\PSoC5\PinLedRed_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFront.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFront_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightRear.h" />
<dep name=".\Generated_Source\PSoC5\PinLightRear_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightSkirting.h" />
<dep name=".\Generated_Source\PSoC5\PinLightSkirting_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinMotionSensor.h" />
<dep name=".\Generated_Source\PSoC5\PinMotionSensor_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmMotor.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmMotor_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmPiezo_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinXbeeSleep.h" />
<dep name=".\Generated_Source\PSoC5\PinXbeeSleep_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PwmMotor.h" />
<dep name=".\Generated_Source\PSoC5\PwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\TimerMainTick.h" />
<dep name=".\Generated_Source\PSoC5\UartDebug.h" />
<dep name=".\Generated_Source\PSoC5\UartXbee.h" />
<dep name=".\Generated_Source\PSoC5\core_cm3.h" />
<dep name=".\Generated_Source\PSoC5\core_cm3_psoc5.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter_cfg.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\project.h" />
<dep name=".\Comms.h" />
<dep name=".\Config.h" />
<dep name=".\Motor.c" />
<dep name=".\Motor.h" />
<dep name=".\device.h" />
<dep name="..\common\PublicObjects.h" />
</file>
<file name=".\Motor.c" />
<file name=".\Motor.h" />
<file name=".\CortexM3\ARM_GCC_441\Debug\Piezo.o">
<dep name=".\Generated_Source\PSoC5\AdcSar.h" />
<dep name=".\Generated_Source\PSoC5\AdcSar_theACLK.h" />
<dep name=".\Generated_Source\PSoC5\CYDEVICE_TRM.H" />
<dep name=".\Generated_Source\PSoC5\CYFITTER.H" />
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\ClockPwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\CyDmac.h" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\CySpc.h" />
<dep name=".\Generated_Source\PSoC5\IsrMainTick.h" />
<dep name=".\Generated_Source\PSoC5\IsrMotionSensor.h" />
<dep name=".\Generated_Source\PSoC5\PinLedGreen.h" />
<dep name=".\Generated_Source\PSoC5\PinLedGreen_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLedOrange.h" />
<dep name=".\Generated_Source\PSoC5\PinLedOrange_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLedRed.h" />
<dep name=".\Generated_Source\PSoC5\PinLedRed_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFront.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFront_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightRear.h" />
<dep name=".\Generated_Source\PSoC5\PinLightRear_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightSkirting.h" />
<dep name=".\Generated_Source\PSoC5\PinLightSkirting_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinMotionSensor.h" />
<dep name=".\Generated_Source\PSoC5\PinMotionSensor_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmMotor.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmMotor_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmPiezo_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinXbeeSleep.h" />
<dep name=".\Generated_Source\PSoC5\PinXbeeSleep_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PwmMotor.h" />
<dep name=".\Generated_Source\PSoC5\PwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\TimerMainTick.h" />
<dep name=".\Generated_Source\PSoC5\UartDebug.h" />
<dep name=".\Generated_Source\PSoC5\UartXbee.h" />
<dep name=".\Generated_Source\PSoC5\core_cm3.h" />
<dep name=".\Generated_Source\PSoC5\core_cm3_psoc5.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter_cfg.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\project.h" />
<dep name=".\Config.h" />
<dep name=".\Piezo.c" />
<dep name=".\Piezo.h" />
<dep name=".\device.h" />
<dep name="..\common\PublicObjects.h" />
</file>
<file name=".\Piezo.c" />
<file name=".\Piezo.h" />
<file name=".\CortexM3\ARM_GCC_441\Debug\main.o">
<dep name=".\Generated_Source\PSoC5\AdcSar.h" />
<dep name=".\Generated_Source\PSoC5\AdcSar_theACLK.h" />
<dep name=".\Generated_Source\PSoC5\CYDEVICE_TRM.H" />
<dep name=".\Generated_Source\PSoC5\CYFITTER.H" />
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\ClockPwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\CyDmac.h" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\CySpc.h" />
<dep name=".\Generated_Source\PSoC5\IsrMainTick.h" />
<dep name=".\Generated_Source\PSoC5\IsrMotionSensor.h" />
<dep name=".\Generated_Source\PSoC5\PinLedGreen.h" />
<dep name=".\Generated_Source\PSoC5\PinLedGreen_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLedOrange.h" />
<dep name=".\Generated_Source\PSoC5\PinLedOrange_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLedRed.h" />
<dep name=".\Generated_Source\PSoC5\PinLedRed_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFront.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFront_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightRear.h" />
<dep name=".\Generated_Source\PSoC5\PinLightRear_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightSkirting.h" />
<dep name=".\Generated_Source\PSoC5\PinLightSkirting_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinMotionSensor.h" />
<dep name=".\Generated_Source\PSoC5\PinMotionSensor_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmMotor.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmMotor_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmPiezo_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinXbeeSleep.h" />
<dep name=".\Generated_Source\PSoC5\PinXbeeSleep_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PwmMotor.h" />
<dep name=".\Generated_Source\PSoC5\PwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\TimerMainTick.h" />
<dep name=".\Generated_Source\PSoC5\UartDebug.h" />
<dep name=".\Generated_Source\PSoC5\UartXbee.h" />
<dep name=".\Generated_Source\PSoC5\core_cm3.h" />
<dep name=".\Generated_Source\PSoC5\core_cm3_psoc5.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter_cfg.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\project.h" />
<dep name=".\Adc.h" />
<dep name=".\Comms.h" />
<dep name=".\Config.h" />
<dep name=".\Lights.h" />
<dep name=".\Motor.h" />
<dep name=".\Piezo.h" />
<dep name=".\device.h" />
<dep name=".\main.c" />
<dep name="..\common\PublicObjects.h" />
</file>
<file name=".\main.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\AdcSar.o">
<dep name=".\Generated_Source\PSoC5\AdcSar.h" />
<dep name=".\Generated_Source\PSoC5\AdcSar_theACLK.h" />
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\AdcSar.c" />
</file>
<file name=".\Generated_Source\PSoC5\AdcSar.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\AdcSar_INT.o">
<dep name=".\Generated_Source\PSoC5\AdcSar.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\AdcSar_INT.c" />
</file>
<file name=".\Generated_Source\PSoC5\AdcSar_INT.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\AdcSar_PM.o">
<dep name=".\Generated_Source\PSoC5\AdcSar.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\AdcSar_PM.c" />
</file>
<file name=".\Generated_Source\PSoC5\AdcSar_PM.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\AdcSar_theACLK.o">
<dep name=".\Generated_Source\PSoC5\AdcSar_theACLK.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\AdcSar_theACLK.c" />
</file>
<file name=".\Generated_Source\PSoC5\AdcSar_theACLK.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\ClockPwmPiezo.o">
<dep name=".\Generated_Source\PSoC5\ClockPwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\ClockPwmPiezo.c" />
</file>
<file name=".\Generated_Source\PSoC5\ClockPwmPiezo.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\Cm3Start.o">
<dep name=".\Generated_Source\PSoC5\CYDEVICE_TRM.H" />
<dep name=".\Generated_Source\PSoC5\CYDMAC.H" />
<dep name=".\Generated_Source\PSoC5\CYFITTER.H" />
<dep name=".\Generated_Source\PSoC5\CYFITTER_CFG.H" />
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\Cm3Start.c" />
</file>
<file name=".\Generated_Source\PSoC5\CYDMAC.H" />
<file name=".\Generated_Source\PSoC5\CYFITTER_CFG.H" />
<file name=".\Generated_Source\PSoC5\Cm3Start.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\CyDmac.o">
<dep name=".\Generated_Source\PSoC5\CYDEVICE_TRM.H" />
<dep name=".\Generated_Source\PSoC5\CYDMAC.H" />
<dep name=".\Generated_Source\PSoC5\CYFITTER.H" />
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\CyDmac.c" />
</file>
<file name=".\Generated_Source\PSoC5\CyDmac.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\CyFlash.o">
<dep name=".\Generated_Source\PSoC5\CYFLASH.H" />
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\Cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\CyFlash.c" />
</file>
<file name=".\Generated_Source\PSoC5\CYFLASH.H" />
<file name=".\Generated_Source\PSoC5\Cydevice_trm.h" />
<file name=".\Generated_Source\PSoC5\CyFlash.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\CyLib.o">
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.c" />
</file>
<file name=".\Generated_Source\PSoC5\CyLib.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\CySpc.o">
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\CySpc.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\CySpc.c" />
</file>
<file name=".\Generated_Source\PSoC5\CySpc.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\IsrMainTick.o">
<dep name=".\Generated_Source\PSoC5\CYDEVICE.H" />
<dep name=".\Generated_Source\PSoC5\CYDEVICE_TRM.H" />
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\IsrMainTick.H" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\IsrMainTick.c" />
</file>
<file name=".\Generated_Source\PSoC5\CYDEVICE.H" />
<file name=".\Generated_Source\PSoC5\IsrMainTick.H" />
<file name=".\Generated_Source\PSoC5\IsrMainTick.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\IsrMotionSensor.o">
<dep name=".\Generated_Source\PSoC5\CYDEVICE.H" />
<dep name=".\Generated_Source\PSoC5\CYDEVICE_TRM.H" />
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\IsrMotionSensor.H" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\IsrMotionSensor.c" />
</file>
<file name=".\Generated_Source\PSoC5\IsrMotionSensor.H" />
<file name=".\Generated_Source\PSoC5\IsrMotionSensor.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PinLedGreen.o">
<dep name=".\Generated_Source\PSoC5\PinLedGreen.h" />
<dep name=".\Generated_Source\PSoC5\PinLedGreen_aliases.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PinLedGreen.c" />
</file>
<file name=".\Generated_Source\PSoC5\PinLedGreen.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PinLedOrange.o">
<dep name=".\Generated_Source\PSoC5\PinLedOrange.h" />
<dep name=".\Generated_Source\PSoC5\PinLedOrange_aliases.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PinLedOrange.c" />
</file>
<file name=".\Generated_Source\PSoC5\PinLedOrange.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PinLedRed.o">
<dep name=".\Generated_Source\PSoC5\PinLedRed.h" />
<dep name=".\Generated_Source\PSoC5\PinLedRed_aliases.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PinLedRed.c" />
</file>
<file name=".\Generated_Source\PSoC5\PinLedRed.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PinLightFront.o">
<dep name=".\Generated_Source\PSoC5\PinLightFront.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFront_aliases.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFront.c" />
</file>
<file name=".\Generated_Source\PSoC5\PinLightFront.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PinLightRear.o">
<dep name=".\Generated_Source\PSoC5\PinLightRear.h" />
<dep name=".\Generated_Source\PSoC5\PinLightRear_aliases.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PinLightRear.c" />
</file>
<file name=".\Generated_Source\PSoC5\PinLightRear.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PinLightSkirting.o">
<dep name=".\Generated_Source\PSoC5\PinLightSkirting.h" />
<dep name=".\Generated_Source\PSoC5\PinLightSkirting_aliases.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PinLightSkirting.c" />
</file>
<file name=".\Generated_Source\PSoC5\PinLightSkirting.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PinMotionSensor.o">
<dep name=".\Generated_Source\PSoC5\PinMotionSensor.h" />
<dep name=".\Generated_Source\PSoC5\PinMotionSensor_aliases.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PinMotionSensor.c" />
</file>
<file name=".\Generated_Source\PSoC5\PinMotionSensor.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PinPwmMotor.o">
<dep name=".\Generated_Source\PSoC5\PinPwmMotor.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmMotor_aliases.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmMotor.c" />
</file>
<file name=".\Generated_Source\PSoC5\PinPwmMotor.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PinPwmPiezo.o">
<dep name=".\Generated_Source\PSoC5\PinPwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmPiezo_aliases.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmPiezo.c" />
</file>
<file name=".\Generated_Source\PSoC5\PinPwmPiezo.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PinXbeeSleep.o">
<dep name=".\Generated_Source\PSoC5\PinXbeeSleep.h" />
<dep name=".\Generated_Source\PSoC5\PinXbeeSleep_aliases.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PinXbeeSleep.c" />
</file>
<file name=".\Generated_Source\PSoC5\PinXbeeSleep.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PwmMotor.o">
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\PwmMotor.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PwmMotor.c" />
</file>
<file name=".\Generated_Source\PSoC5\PwmMotor.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PwmMotor_PM.o">
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\PwmMotor.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PwmMotor_PM.c" />
</file>
<file name=".\Generated_Source\PSoC5\PwmMotor_PM.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PwmPiezo.o">
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\PwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PwmPiezo.c" />
</file>
<file name=".\Generated_Source\PSoC5\PwmPiezo.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PwmPiezo_PM.o">
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\PwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PwmPiezo_PM.c" />
</file>
<file name=".\Generated_Source\PSoC5\PwmPiezo_PM.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\TimerMainTick.o">
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\TimerMainTick.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\TimerMainTick.c" />
</file>
<file name=".\Generated_Source\PSoC5\TimerMainTick.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\TimerMainTick_PM.o">
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\TimerMainTick.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\TimerMainTick_PM.c" />
</file>
<file name=".\Generated_Source\PSoC5\TimerMainTick_PM.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\UartDebug.o">
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\UartDebug.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\UartDebug.c" />
</file>
<file name=".\Generated_Source\PSoC5\UartDebug.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\UartDebug_INT.o">
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\UartDebug.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\UartDebug_INT.c" />
</file>
<file name=".\Generated_Source\PSoC5\UartDebug_INT.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\UartDebug_PM.o">
<dep name=".\Generated_Source\PSoC5\UartDebug.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\UartDebug_PM.c" />
</file>
<file name=".\Generated_Source\PSoC5\UartDebug_PM.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\UartXbee.o">
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\UartXbee.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\UartXbee.c" />
</file>
<file name=".\Generated_Source\PSoC5\UartXbee.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\UartXbee_INT.o">
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\UartXbee.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\UartXbee_INT.c" />
</file>
<file name=".\Generated_Source\PSoC5\UartXbee_INT.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\UartXbee_PM.o">
<dep name=".\Generated_Source\PSoC5\UartXbee.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\UartXbee_PM.c" />
</file>
<file name=".\Generated_Source\PSoC5\UartXbee_PM.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\cyPm.o">
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.c" />
</file>
<file name=".\Generated_Source\PSoC5\cyPm.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\cyfitter_cfg.o">
<dep name=".\Generated_Source\PSoC5\CYDEVICE_TRM.H" />
<dep name=".\Generated_Source\PSoC5\CYFITTER.H" />
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyDmac.h" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter_cfg.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter_cfg.c" />
</file>
<file name=".\Generated_Source\PSoC5\cyfitter_cfg.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\cyutils.o">
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\cyutils.c" />
</file>
<file name=".\Generated_Source\PSoC5\cyutils.c" />
<file name="..\Skateboard Remote.cydsn\Adc.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\Alarm.o">
<dep name=".\Generated_Source\PSoC5\CYDEVICE_TRM.H" />
<dep name=".\Generated_Source\PSoC5\CYFITTER.H" />
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\ClockPwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\CyDmac.h" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\CySpc.h" />
<dep name=".\Generated_Source\PSoC5\IsrMainTick.h" />
<dep name=".\Generated_Source\PSoC5\IsrMotionSensor.h" />
<dep name=".\Generated_Source\PSoC5\PinLedGreen.h" />
<dep name=".\Generated_Source\PSoC5\PinLedGreen_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLedOrange.h" />
<dep name=".\Generated_Source\PSoC5\PinLedOrange_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLedRed.h" />
<dep name=".\Generated_Source\PSoC5\PinLedRed_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFront.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFront_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightRear.h" />
<dep name=".\Generated_Source\PSoC5\PinLightRear_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinLightSkirting.h" />
<dep name=".\Generated_Source\PSoC5\PinLightSkirting_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinMotionSensor.h" />
<dep name=".\Generated_Source\PSoC5\PinMotionSensor_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmMotor.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmMotor_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\PinPwmPiezo_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PinXbeeSleep.h" />
<dep name=".\Generated_Source\PSoC5\PinXbeeSleep_aliases.h" />
<dep name=".\Generated_Source\PSoC5\PwmMotor.h" />
<dep name=".\Generated_Source\PSoC5\PwmPiezo.h" />
<dep name=".\Generated_Source\PSoC5\TimerMainTick.h" />
<dep name=".\Generated_Source\PSoC5\UartDebug.h" />
<dep name=".\Generated_Source\PSoC5\UartXbee.h" />
<dep name=".\Generated_Source\PSoC5\core_cm3.h" />
<dep name=".\Generated_Source\PSoC5\core_cm3_psoc5.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter_cfg.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\project.h" />
<dep name=".\Alarm.c" />
<dep name=".\Alarm.h" />
<dep name=".\Config.h" />
<dep name=".\device.h" />
</file>
<file name=".\Alarm.c" />
<file name=".\Alarm.h" />
<file name="..\common\Comms.h" />
<file name="..\common\Comms.c" />
<file name=".\Generated_Source\PSoC5\PinLightFrontLeft.h" />
<file name=".\Generated_Source\PSoC5\PinLightFrontLeft_aliases.h" />
<file name=".\Generated_Source\PSoC5\PinLightFrontRight.h" />
<file name=".\Generated_Source\PSoC5\PinLightFrontRight_aliases.h" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PinLightFrontLeft.o">
<dep name=".\Generated_Source\PSoC5\PinLightFrontLeft.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFrontLeft_aliases.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFrontLeft.c" />
</file>
<file name=".\Generated_Source\PSoC5\PinLightFrontLeft.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PinLightFrontRight.o">
<dep name=".\Generated_Source\PSoC5\PinLightFrontRight.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFrontRight_aliases.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PinLightFrontRight.c" />
</file>
<file name=".\Generated_Source\PSoC5\PinLightFrontRight.c" />
<file name=".\Generated_Source\PSoC5\ClockPwmMotor.h" />
<file name=".\CortexM3\ARM_GCC_441\Debug\ClockPwmMotor.o">
<dep name=".\Generated_Source\PSoC5\ClockPwmMotor.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\ClockPwmMotor.c" />
</file>
<file name=".\Generated_Source\PSoC5\ClockPwmMotor.c" />
<file name=".\Generated_Source\PSoC5\ISR_MOTION_ALARM.h" />
<file name=".\Generated_Source\PSoC5\PIN_MOTION_ALARM.h" />
<file name=".\Generated_Source\PSoC5\PIN_MOTION_ALARM_aliases.h" />
<file name=".\CortexM3\ARM_GCC_441\Debug\ISR_MOTION_ALARM.o">
<dep name=".\Generated_Source\PSoC5\CYDEVICE.H" />
<dep name=".\Generated_Source\PSoC5\CYDEVICE_TRM.H" />
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\ISR_MOTION_ALARM.H" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\ISR_MOTION_ALARM.c" />
</file>
<file name=".\Generated_Source\PSoC5\ISR_MOTION_ALARM.H" />
<file name=".\Generated_Source\PSoC5\ISR_MOTION_ALARM.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PIN_MOTION_ALARM.o">
<dep name=".\Generated_Source\PSoC5\PIN_MOTION_ALARM.h" />
<dep name=".\Generated_Source\PSoC5\PIN_MOTION_ALARM_aliases.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PIN_MOTION_ALARM.c" />
</file>
<file name=".\Generated_Source\PSoC5\PIN_MOTION_ALARM.c" />
<file name=".\Generated_Source\PSoC5\Clock_1.h" />
<file name=".\Generated_Source\PSoC5\Clock_2.h" />
<file name=".\Generated_Source\PSoC5\PIN_PIEZO_PWM1.h" />
<file name=".\Generated_Source\PSoC5\PIN_PIEZO_PWM1_aliases.h" />
<file name=".\Generated_Source\PSoC5\PIN_PIEZO_PWM2.h" />
<file name=".\Generated_Source\PSoC5\PIN_PIEZO_PWM2_aliases.h" />
<file name=".\Generated_Source\PSoC5\PIN_PWM.h" />
<file name=".\Generated_Source\PSoC5\PIN_PWM_aliases.h" />
<file name=".\CortexM3\ARM_GCC_441\Debug\Clock_1.o">
<dep name=".\Generated_Source\PSoC5\Clock_1.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\Clock_1.c" />
</file>
<file name=".\Generated_Source\PSoC5\Clock_1.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\Clock_2.o">
<dep name=".\Generated_Source\PSoC5\Clock_2.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\Clock_2.c" />
</file>
<file name=".\Generated_Source\PSoC5\Clock_2.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PIN_PIEZO_PWM1.o">
<dep name=".\Generated_Source\PSoC5\PIN_PIEZO_PWM1.h" />
<dep name=".\Generated_Source\PSoC5\PIN_PIEZO_PWM1_aliases.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PIN_PIEZO_PWM1.c" />
</file>
<file name=".\Generated_Source\PSoC5\PIN_PIEZO_PWM1.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PIN_PIEZO_PWM2.o">
<dep name=".\Generated_Source\PSoC5\PIN_PIEZO_PWM2.h" />
<dep name=".\Generated_Source\PSoC5\PIN_PIEZO_PWM2_aliases.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PIN_PIEZO_PWM2.c" />
</file>
<file name=".\Generated_Source\PSoC5\PIN_PIEZO_PWM2.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PIN_PWM.o">
<dep name=".\Generated_Source\PSoC5\PIN_PWM.h" />
<dep name=".\Generated_Source\PSoC5\PIN_PWM_aliases.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PIN_PWM.c" />
</file>
<file name=".\Generated_Source\PSoC5\PIN_PWM.c" />
<file name=".\Generated_Source\PSoC5\ADC_SAR.h" />
<file name=".\Generated_Source\PSoC5\ADC_SAR_Bypass.h" />
<file name=".\Generated_Source\PSoC5\ADC_SAR_Bypass_aliases.h" />
<file name=".\Generated_Source\PSoC5\ADC_SAR_theACLK.h" />
<file name=".\Generated_Source\PSoC5\PIN_POT_aliases.h" />
<file name=".\Generated_Source\PSoC5\PinLedPcbGreen.h" />
<file name=".\Generated_Source\PSoC5\PinLedPcbGreen_aliases.h" />
<file name=".\Generated_Source\PSoC5\PinLedPcbOrange.h" />
<file name=".\Generated_Source\PSoC5\PinLedPcbOrange_aliases.h" />
<file name=".\Generated_Source\PSoC5\PinLedPcbRed.h" />
<file name=".\Generated_Source\PSoC5\PinLedPcbRed_aliases.h" />
<file name=".\CortexM3\ARM_GCC_441\Debug\Sleep.o">
<dep name=".\Sleep.c" />
</file>
<file name=".\Sleep.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\ADC_SAR.o">
<dep name=".\Generated_Source\PSoC5\ADC_SAR.h" />
<dep name=".\Generated_Source\PSoC5\ADC_SAR_theACLK.h" />
<dep name=".\Generated_Source\PSoC5\CYLIB.H" />
<dep name=".\Generated_Source\PSoC5\CYSPC.H" />
<dep name=".\Generated_Source\PSoC5\CYTYPES.H" />
<dep name=".\Generated_Source\PSoC5\CyFlash.h" />
<dep name=".\Generated_Source\PSoC5\CyLib.h" />
<dep name=".\Generated_Source\PSoC5\cyPm.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\ADC_SAR.c" />
</file>
<file name=".\Generated_Source\PSoC5\ADC_SAR.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\ADC_SAR_Bypass.o">
<dep name=".\Generated_Source\PSoC5\ADC_SAR_Bypass.h" />
<dep name=".\Generated_Source\PSoC5\ADC_SAR_Bypass_aliases.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\ADC_SAR_Bypass.c" />
</file>
<file name=".\Generated_Source\PSoC5\ADC_SAR_Bypass.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\ADC_SAR_INT.o">
<dep name=".\Generated_Source\PSoC5\ADC_SAR.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\ADC_SAR_INT.c" />
</file>
<file name=".\Generated_Source\PSoC5\ADC_SAR_INT.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\ADC_SAR_PM.o">
<dep name=".\Generated_Source\PSoC5\ADC_SAR.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\ADC_SAR_PM.c" />
</file>
<file name=".\Generated_Source\PSoC5\ADC_SAR_PM.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\ADC_SAR_theACLK.o">
<dep name=".\Generated_Source\PSoC5\ADC_SAR_theACLK.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\ADC_SAR_theACLK.c" />
</file>
<file name=".\Generated_Source\PSoC5\ADC_SAR_theACLK.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PinLedPcbGreen.o">
<dep name=".\Generated_Source\PSoC5\PinLedPcbGreen.h" />
<dep name=".\Generated_Source\PSoC5\PinLedPcbGreen_aliases.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PinLedPcbGreen.c" />
</file>
<file name=".\Generated_Source\PSoC5\PinLedPcbGreen.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PinLedPcbOrange.o">
<dep name=".\Generated_Source\PSoC5\PinLedPcbOrange.h" />
<dep name=".\Generated_Source\PSoC5\PinLedPcbOrange_aliases.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PinLedPcbOrange.c" />
</file>
<file name=".\Generated_Source\PSoC5\PinLedPcbOrange.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\PinLedPcbRed.o">
<dep name=".\Generated_Source\PSoC5\PinLedPcbRed.h" />
<dep name=".\Generated_Source\PSoC5\PinLedPcbRed_aliases.h" />
<dep name=".\Generated_Source\PSoC5\cydevice.h" />
<dep name=".\Generated_Source\PSoC5\cydevice_trm.h" />
<dep name=".\Generated_Source\PSoC5\cyfitter.h" />
<dep name=".\Generated_Source\PSoC5\cypins.h" />
<dep name=".\Generated_Source\PSoC5\cytypes.h" />
<dep name=".\Generated_Source\PSoC5\PinLedPcbRed.c" />
</file>
<file name=".\Generated_Source\PSoC5\PinLedPcbRed.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\core_cm3.o">
<dep name=".\Generated_Source\PSoC5\core_cm3.c" />
</file>
<file name=".\Generated_Source\PSoC5\core_cm3.c" />
<file name=".\CortexM3\ARM_GCC_441\Debug\CyBootAsmGnu.o">
<dep name=".\Generated_Source\PSoC5\CyBootAsmGnu.s" />
</file>
<file name=".\Generated_Source\PSoC5\CyBootAsmGnu.s" />
</CyGuid_1173175f-1b9b-4ad4-a065-754a48a27021>
</dependency_info>
</CyGuid_f44455c5-3770-4452-b988-0a7a7ff46256>
</name>
<name v="link_deps">
<CyGuid_f44455c5-3770-4452-b988-0a7a7ff46256 type_name="CyDesigner.Common.ProjMgmt.Model.CyConfigDependencies" version="1">
<dependency_info name="c9323d49-d323-40b8-9b59-cc008d68a989@Debug@CortexM3" xml_contents_version="2">
<CyGuid_1173175f-1b9b-4ad4-a065-754a48a27021 type_name="CyDesigner.Common.Base.CyFileDeps" version="1">
<file name=".\CortexM3\ARM_GCC_441\Debug\Skateboard Motherboard.hex">
<dep name=".\CortexM3\ARM_GCC_441\Debug\main.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\Sleep.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\Piezo.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\Led.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\Lights.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\Motor.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\Comms.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\Adc.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\Cm3Start.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\core_cm3.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\CyBootAsmGnu.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\CyDmac.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\CyFlash.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\CyLib.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\cyPm.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\CySpc.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\cyutils.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\PwmMotor.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\PwmMotor_PM.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\PwmPiezo.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\PwmPiezo_PM.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\PinLedGreen.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\PinLedOrange.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\PinLedRed.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\PinLightRear.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\PinLightSkirting.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\UartXbee.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\UartXbee_PM.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\UartXbee_INT.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\PinXbeeSleep.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\TimerMainTick.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\TimerMainTick_PM.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\IsrMainTick.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\PinPwmMotor.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\ClockPwmPiezo.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\PinPwmPiezo.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\PinMotionSensor.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\IsrMotionSensor.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\UartDebug.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\UartDebug_PM.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\UartDebug_INT.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\PinLightFront.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\AdcSar.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\AdcSar_INT.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\AdcSar_PM.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\AdcSar_theACLK.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\cyfitter_cfg.o" />
<dep name=".\CortexM3\ARM_GCC_441\Debug\Skateboard Motherboard.a" />
<dep name="${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\CortexM3\ARM_GCC_441\Debug\CyComponentLibrary.a" />
</file>
</CyGuid_1173175f-1b9b-4ad4-a065-754a48a27021>
</dependency_info>
</CyGuid_f44455c5-3770-4452-b988-0a7a7ff46256>
</name>
</CyGuid_47ec7058-2f43-4a2f-ae73-172624e235df>
</dataGuid>
<dataGuid v="b0374e30-ce3a-47f2-ad85-821643292c68">
<CyGuid_b0374e30-ce3a-47f2-ad85-821643292c68 type_name="CyDesigner.Common.ProjMgmt.Common.CyCmdLineData" version="2">
<genericCmdLineData>
<name v="c9323d49-d323-40b8-9b59-cc008d68a989@Debug@CortexM3">
<name_val_pair name=".\main.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PinLedPcbGreen.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PinLedPcbOrange.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PinLedPcbRed.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\Cm3Start.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\core_cm3.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\CyBootAsmGnu.s" v="&quot;-I. &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-g &quot;&quot;-alh=${OutputDir}/${CompileFile}.lst &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\CyDmac.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\CyFlash.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\CyLib.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\cyPm.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\CySpc.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\cyutils.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\cyfitter_cfg.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name="C:\Users\Geo\Documents\Projects\Electric Skateboard\Code\PSoC\Skateboard Motherboard.cydsn\CortexM3\ARM_GCC_441\Debug\Skateboard Motherboard.hex" v="&quot;-mthumb &quot;&quot;-march=armv7-m &quot;&quot;-mfix-cortex-m3-ldrd &quot;&quot;-T &quot;&quot;.\Generated_Source\PSoC5\cm3gcc.ld &quot;&quot;-g &quot;&quot;-Wl,-Map,${OutputDir}\${ProjectShortName}.map &quot;&quot;-Wl,--gc-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PwmMotor.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PwmMotor_PM.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PIN_PWM.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\Clock_1.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\ADC_SAR.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\ADC_SAR_INT.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\ADC_SAR_PM.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PwmPiezo.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PwmPiezo_PM.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\Clock_2.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PIN_PIEZO_PWM1.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PIN_PIEZO_PWM2.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PIN_MOTION_ALARM.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\ISR_MOTION_ALARM.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\ADC_SAR_theACLK.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\ADC_SAR_Bypass.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Sleep.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Alarm.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Led.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Piezo.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name="C:\Users\Geo\Documents\Projects\Electric Skateboard\Firmware\PSoC\Skateboard Motherboard.cydsn\CortexM3\ARM_GCC_441\Debug\Skateboard Motherboard.hex" v="&quot;-mthumb &quot;&quot;-march=armv7-m &quot;&quot;-mfix-cortex-m3-ldrd &quot;&quot;-T &quot;&quot;.\Generated_Source\PSoC5\cm3gcc.ld &quot;&quot;-g &quot;&quot;-Wl,-Map,${OutputDir}\${ProjectShortName}.map &quot;&quot;-Wl,--gc-sections &quot;" />
<name_val_pair name=".\Lights.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PinLedGreen.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PinLedOrange.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PinLedRed.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PinLightFrontLeft.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PinLightFrontRight.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PinLightRear.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PinLightSkirting.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name="..\common\Comms.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\UartXbee.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\UartXbee_PM.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\UartXbee_INT.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PinXbeeSleep.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\TimerMainTick.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\TimerMainTick_PM.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\IsrMainTick.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PinPwmMotor.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\ClockPwmMotor.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\ClockPwmPiezo.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PinPwmPiezo.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PinMotionSensor.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\IsrMotionSensor.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Motor.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\UartDebug.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\UartDebug_PM.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\UartDebug_INT.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\PinLightFront.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Comms.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name="..\Skateboard Remote.cydsn\Adc.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\ADC_SAR_1.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\ADC_SAR_1_INT.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\ADC_SAR_1_PM.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\ADC_SAR_1_theACLK.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\AdcSar.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\AdcSar_INT.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\AdcSar_PM.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Generated_Source\PSoC5\AdcSar_theACLK.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
<name_val_pair name=".\Adc.c" v="&quot;-I. &quot;&quot;-Wno-main &quot;&quot;-I./Generated_Source/PSoC5 &quot;&quot;-mcpu=cortex-m3 &quot;&quot;-mthumb &quot;&quot;-Wall &quot;&quot;-g &quot;&quot;-Wa,-alh=${OutputDir}\${CompileFile}.lst &quot;&quot;-ffunction-sections &quot;" />
</name>
</genericCmdLineData>
<codeGenCmdLineTag v="&quot;-.appdatapath&quot; &quot;C:\Users\Geo\AppData\Local\Cypress Semiconductor\PSoC Creator\2.0&quot; &quot;-.fdsnotice&quot; &quot;-.fdswarpdepfile=warp_dependencies.txt&quot; &quot;-.fdselabdepfile=elab_dependencies.txt&quot; &quot;-.fdsbldfile=generated_files.txt&quot; &quot;-p&quot; &quot;C:\Users\Geo\Documents\Projects\Electric Skateboard\Firmware\PSoC\Skateboard Motherboard.cydsn\Skateboard Motherboard.cyprj&quot; &quot;-d&quot; &quot;CY8C5246AXI-054&quot; &quot;-s&quot; &quot;C:\Users\Geo\Documents\Projects\Electric Skateboard\Firmware\PSoC\Skateboard Motherboard.cydsn\Generated_Source\PSoC5&quot; &quot;-w&quot; &quot;0&quot; &quot;--&quot; &quot;-yv2&quot; &quot;-w&quot; &quot;0&quot; &quot;-v3&quot; &quot;-ygs&quot; &quot;-q10&quot; &quot;-o2&quot; &quot;-.fftcfgtype=LE&quot; " />
</CyGuid_b0374e30-ce3a-47f2-ad85-821643292c68>
</dataGuid>
<dataGuid v="597c5b74-0c46-4204-8b7f-96f3570671dc">
<CyGuid_597c5b74-0c46-4204-8b7f-96f3570671dc type_name="CyDesigner.Common.ProjMgmt.DeviceSelector.CyDeviceSelectorState" version="1">
<name_val_pair name="Dialog Bounds" v="-1230, 116, 800, 598" />
<name_val_pair name="Column Order" v="PartNumber;DesignFits;Architecture;SPEED_MHZ;FLASH_BYTES;SRAM_BYTES;EEPROM_BYTES;TRACEBUFF_BYTES;DMACHANNELS_COUNT;PLL_COUNT;DIRDRIVELCD;CAPSENSE;PVT_COMPLEX_ADC;DAC8_COUNT;ANALOGBLOCKS_COUNT;DFB_COUNT;COMP_COUNT;OPAMP_COUNT;USB_TYPE;CAN20B_COUNT;UDB_COUNT;TIMERCOUNTERPWM_COUNT;GPIO_COUNT;SIO_COUNT;USBIO_COUNT;BOOSTCONVERTER_VOLTS;VDDMIN_VOLTS;VDDMAX_VOLTS;AUTOMOTIVE_QUALIFIED;TEMPMIN_CELSIUS;TEMPMAX_CELSIUS;PACKAGE;JTAGID;ETM;" />
<name_val_pair name="Filter Options" v="Architecture:PSoC5;" />
<name_val_pair name="Visible Columns" v="PartNumber;DesignFits;Architecture;SPEED_MHZ;FLASH_BYTES;SRAM_BYTES;EEPROM_BYTES;TRACEBUFF_BYTES;DMACHANNELS_COUNT;PLL_COUNT;DIRDRIVELCD;CAPSENSE;PVT_COMPLEX_ADC;DAC8_COUNT;ANALOGBLOCKS_COUNT;DFB_COUNT;" />
<name_val_pair name="Sort" v="PartNumber;Ascending" />
</CyGuid_597c5b74-0c46-4204-8b7f-96f3570671dc>
</dataGuid>
<dataGuid v="925cc1e1-309e-4e08-b0a1-09a83c35b157">
<CyGuid_925cc1e1-309e-4e08-b0a1-09a83c35b157 type_name="CyDesigner.Common.ProjMgmt.Model.CyPrjMgmtProjectPSoCExe+CyCodeGenDepUserInfo" version="1">
<deps_list>
<v>.\TopDesign\TopDesign.cysch</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\aliases.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\aliases.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\aliases.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\PWM_v2_10.cysch</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\PWM_v2_10.cysym</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\PWM_v2_10.pdf</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\PWM_v2_10.cystate</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\API\PWM.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\API\PWM.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\API\PWM_PM.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\Custom\cypwmcontrol.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\Custom\cypwmcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\Custom\cypwmcontroladv.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\Custom\cypwmcontroladv.Designer.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\Custom\CyPWMCustomizer.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\Custom\PWMParameters.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\Custom\cypwmcontrol.resx</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\Custom\cypwmcontroladv.resx</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\B_PWM_v2_10\B_PWM_v2_10.cysym</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\B_PWM_v2_10\B_PWM_v2_10.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\OneTerminal\OneTerminal.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\OneTerminal\OneTerminal.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\OneTerminal\OneTerminal.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\aliases.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\aliases.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\API\clk.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\API\clk.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\UART_v2_10.cysch</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\UART_v2_10.cysym</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\UART_v2_10.pdf</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\UART_v2_10.cystate</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\API\UART.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\API\UART.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\API\UART_PM.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\API\UARTINT.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\Custom\cyuartadvancedcontrol.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\Custom\cyuartadvancedcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\Custom\cyuartcontrol.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\Custom\cyuartcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\Custom\cyuartcustomizer.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\Custom\cyuartparameters.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\Custom\Resources.Designer.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\Custom\cyuartadvancedcontrol.resx</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\Custom\cyuartcontrol.resx</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\Custom\Resources.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.primitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\PSoC5\API\intc.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\PSoC5\API\intc.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\API\clk.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\API\clk.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.primitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\PSoC5\API\intc.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\PSoC5\API\intc.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\B_UART_v2_10\B_UART_v2_10.cysym</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\B_UART_v2_10\B_UART_v2_10.v</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\PWM_v2_10.cysch</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\PWM_v2_10.cysym</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\PWM_v2_10.pdf</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\PWM_v2_10.cystate</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\API\PWM.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\API\PWM.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\API\PWM_PM.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\Custom\cypwmcontrol.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\Custom\cypwmcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\Custom\cypwmcontroladv.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\Custom\cypwmcontroladv.Designer.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\Custom\CyPWMCustomizer.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\Custom\PWMParameters.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\Custom\cypwmcontrol.resx</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\PWM_v2_10\Custom\cypwmcontroladv.resx</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\B_PWM_v2_10\B_PWM_v2_10.cysym</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\B_PWM_v2_10\B_PWM_v2_10.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\OneTerminal\OneTerminal.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\OneTerminal\OneTerminal.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\OneTerminal\OneTerminal.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\API\clk.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\API\clk.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\aliases.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\aliases.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.primitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\PSoC5\API\intc.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\PSoC5\API\intc.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\aliases.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\aliases.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\aliases.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\aliases.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\aliases.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\Timer_v2_20\Timer_v2_20.cycdx</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\Timer_v2_20\Timer_v2_20.cysch</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\Timer_v2_20\Timer_v2_20.cysym</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\Timer_v2_20\Timer_v2_20.pdf</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\Timer_v2_20\Timer_v2_20.cystate</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\Timer_v2_20\API\Timer.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\Timer_v2_20\API\Timer.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\Timer_v2_20\API\Timer_PM.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\Timer_v2_20\Custom\cytimercontrol.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\Timer_v2_20\Custom\cytimercontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\Timer_v2_20\Custom\CyTimerCustomizer.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\Timer_v2_20\Custom\TimerParameters.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\Timer_v2_20\Custom\cytimercontrol.resx</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\Timer_v2_20</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\B_Timer_v2_20\B_Timer_v2_20.cysym</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\B_Timer_v2_20\B_Timer_v2_20.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\OneTerminal\OneTerminal.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\OneTerminal\OneTerminal.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\OneTerminal\OneTerminal.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\API\clk.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\API\clk.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.primitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\PSoC5\API\intc.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\PSoC5\API\intc.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\UART_v2_10.cysch</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\UART_v2_10.cysym</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\UART_v2_10.pdf</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\UART_v2_10.cystate</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\API\UART.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\API\UART.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\API\UART_PM.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\API\UARTINT.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\Custom\cyuartadvancedcontrol.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\Custom\cyuartadvancedcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\Custom\cyuartcontrol.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\Custom\cyuartcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\Custom\cyuartcustomizer.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\Custom\cyuartparameters.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\Custom\Resources.Designer.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\Custom\cyuartadvancedcontrol.resx</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\Custom\cyuartcontrol.resx</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\UART_v2_10\Custom\Resources.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.primitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\PSoC5\API\intc.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\PSoC5\API\intc.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\API\clk.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\API\clk.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.primitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\PSoC5\API\intc.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\PSoC5\API\intc.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\B_UART_v2_10\B_UART_v2_10.cysym</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\B_UART_v2_10\B_UART_v2_10.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\aliases.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\aliases.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibraryupdates\CyComponentLibraryUpdates.cylib\ADC_SAR_v1_71\ADC_SAR_v1_71.cysym</v>
<v>${CyRoot}\psoc\content\cycomponentlibraryupdates\CyComponentLibraryUpdates.cylib\ADC_SAR_v1_71\ADC_SAR_v1_71.pdf</v>
<v>${CyRoot}\psoc\content\cycomponentlibraryupdates\CyComponentLibraryUpdates.cylib\ADC_SAR_v1_71\ADC_SAR_v1_71.cycdx</v>
<v>${CyRoot}\psoc\content\cycomponentlibraryupdates\CyComponentLibraryUpdates.cylib\ADC_SAR_v1_71\ADC_SAR_v1_71.cystate</v>
<v>${CyRoot}\psoc\content\cycomponentlibraryupdates\CyComponentLibraryUpdates.cylib\ADC_SAR_v1_71\Custom\cyadcsarcontrol.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibraryupdates\CyComponentLibraryUpdates.cylib\ADC_SAR_v1_71\Custom\cyadcsarcontrol.designer.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibraryupdates\CyComponentLibraryUpdates.cylib\ADC_SAR_v1_71\Custom\cyadcsarcustomizer.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibraryupdates\CyComponentLibraryUpdates.cylib\ADC_SAR_v1_71\Custom\cyadcsarparameters.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibraryupdates\CyComponentLibraryUpdates.cylib\ADC_SAR_v1_71\Custom\cydictparser.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibraryupdates\CyComponentLibraryUpdates.cylib\ADC_SAR_v1_71\Custom\cyclockreader.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibraryupdates\CyComponentLibraryUpdates.cylib\ADC_SAR_v1_71\Custom\Resources.Designer.cs</v>
<v>${CyRoot}\psoc\content\cycomponentlibraryupdates\CyComponentLibraryUpdates.cylib\ADC_SAR_v1_71\Custom\cyadcsarcontrol.resx</v>
<v>${CyRoot}\psoc\content\cycomponentlibraryupdates\CyComponentLibraryUpdates.cylib\ADC_SAR_v1_71\Custom\Resources.resx</v>
<v>${CyRoot}\psoc\content\cycomponentlibraryupdates\CyComponentLibraryUpdates.cylib\ADC_SAR_v1_71\PSoC5\ADC_SAR_v1_71.cydmacap</v>
<v>${CyRoot}\psoc\content\cycomponentlibraryupdates\CyComponentLibraryUpdates.cylib\ADC_SAR_v1_71\PSoC5\ADC_SAR_v1_71.cysch</v>
<v>${CyRoot}\psoc\content\cycomponentlibraryupdates\CyComponentLibraryUpdates.cylib\ADC_SAR_v1_71\PSoC5\API\ADC_SAR.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibraryupdates\CyComponentLibraryUpdates.cylib\ADC_SAR_v1_71\PSoC5\API\ADC_SAR.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibraryupdates\CyComponentLibraryUpdates.cylib\ADC_SAR_v1_71\PSoC5\API\ADC_SAR_INT.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibraryupdates\CyComponentLibraryUpdates.cylib\ADC_SAR_v1_71\PSoC5\API\ADC_SAR_PM.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_virtualmux_v1_0\cy_analog_virtualmux_v1_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_virtualmux_v1_0\cy_analog_virtualmux_v1_0.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_virtualmux_v1_0\cy_analog_virtualmux_v1_0.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_virtualmux_v1_0\Custom\cy_analog_virtualmux_v1_0.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.primitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\cy_isr_v1_50.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\PSoC5\API\intc.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_isr_v1_50\PSoC5\API\intc.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\cy_clock_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\API\clk.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\API\clk.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_clock_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_psoc5_sar_v2_0\cy_psoc5_sar_v2_0.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_psoc5_sar_v2_0\cy_psoc5_sar_v2_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_virtualmux_v1_0\cy_analog_virtualmux_v1_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_virtualmux_v1_0\cy_analog_virtualmux_v1_0.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_virtualmux_v1_0\cy_analog_virtualmux_v1_0.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_virtualmux_v1_0\Custom\cy_analog_virtualmux_v1_0.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_virtualmux_v1_0\cy_analog_virtualmux_v1_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_virtualmux_v1_0\cy_analog_virtualmux_v1_0.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_virtualmux_v1_0\cy_analog_virtualmux_v1_0.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_virtualmux_v1_0\Custom\cy_analog_virtualmux_v1_0.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_noconnect_v1_0\cy_analog_noconnect_v1_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_noconnect_v1_0\cy_analog_noconnect_v1_0.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_noconnect_v1_0\cy_analog_noconnect_v1_0.primitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_noconnect_v1_0\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_vref_v1_50\cy_vref_v1_50.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_vref_v1_50\cy_vref_v1_50.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_vref_v1_50\cy_vref_v1_50.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_vref_v1_50\cy_vref_v1_50.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_vref_v1_50\cy_vref_v1_50.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_vref_v1_50\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_vref_v1_50\Custom\cyvrefidcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_vref_v1_50\Custom\cyvrefidcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_vref_v1_50\Custom\cyvrefidcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_virtualmux_v1_0\cy_analog_virtualmux_v1_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_virtualmux_v1_0\cy_analog_virtualmux_v1_0.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_virtualmux_v1_0\cy_analog_virtualmux_v1_0.v</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_virtualmux_v1_0\Custom\cy_analog_virtualmux_v1_0.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_noconnect_v1_0\cy_analog_noconnect_v1_0.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_noconnect_v1_0\cy_analog_noconnect_v1_0.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_noconnect_v1_0\cy_analog_noconnect_v1_0.primitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_noconnect_v1_0\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cyprimitive</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cysym</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.pdf</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\cy_pins_v1_60.cystate</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\custom.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.Designer.cs</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cygeneralcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyinputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cymappingcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyoutputcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinaliasdialog.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cypinscontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cyporcontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\cytypecontrol.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\Custom\Resource1.resx</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\aliases.h</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.c</v>
<v>${CyRoot}\psoc\content\cyprimitives\CyPrimitives.cylib\cy_pins_v1_60\PSoC5\API\pins.h</v>
<v>.\Skateboard Motherboard.cydwr</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\cm3gcc.ld</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\Cm3RealView.scat</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\Cm3Start.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\core_cm3.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\core_cm3.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\core_cm3_psoc5.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\CyBootAsmGnu.s</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\CyBootAsmRv.s</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\cybtldr.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\cybtldr.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\cybtldr_common.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\cybtldr_common.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\cybtldr_loadable.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\cybtldr_loadable.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\CyDmac.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\CyDmac.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\CyFlash.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\CyFlash.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\CyLib.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\CyLib.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\cypins.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\cyPm.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\cyPm.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\CySpc.c</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\CySpc.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\cytypes.h</v>
<v>${CyRoot}\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\cy_boot_v2_40\PSoC5\API\cyutils.c</v>
</deps_list>
<gen_list>
<v>.\Generated_Source\PSoC5\cyfitter_cfg.h</v>
<v>.\Generated_Source\PSoC5\cyfitter_cfg.c</v>
<v>.\Generated_Source\PSoC5\config.hex</v>
<v>.\Generated_Source\PSoC5\protect.hex</v>
<v>.\Generated_Source\PSoC5\cydevice.h</v>
<v>.\Generated_Source\PSoC5\cydevicegnu.inc</v>
<v>.\Generated_Source\PSoC5\cydevicerv.inc</v>
<v>.\Generated_Source\PSoC5\cydevice_trm.h</v>
<v>.\Generated_Source\PSoC5\cydevicegnu_trm.inc</v>
<v>.\Generated_Source\PSoC5\cydevicerv_trm.inc</v>
<v>.\Generated_Source\PSoC5\cyfittergnu.inc</v>
<v>.\Generated_Source\PSoC5\cyfitterrv.inc</v>
<v>.\Generated_Source\PSoC5\cyfitter.h</v>
<v>.\Generated_Source\PSoC5\PinLedPcbGreen_aliases.h</v>
<v>.\Generated_Source\PSoC5\PinLedPcbGreen.c</v>
<v>.\Generated_Source\PSoC5\PinLedPcbGreen.h</v>
<v>.\Generated_Source\PSoC5\PinLedPcbOrange_aliases.h</v>
<v>.\Generated_Source\PSoC5\PinLedPcbOrange.c</v>
<v>.\Generated_Source\PSoC5\PinLedPcbOrange.h</v>
<v>.\Generated_Source\PSoC5\PinLedPcbRed_aliases.h</v>
<v>.\Generated_Source\PSoC5\PinLedPcbRed.c</v>
<v>.\Generated_Source\PSoC5\PinLedPcbRed.h</v>
<v>.\Generated_Source\PSoC5\cm3gcc.ld</v>
<v>.\Generated_Source\PSoC5\Cm3RealView.scat</v>
<v>.\Generated_Source\PSoC5\Cm3Start.c</v>
<v>.\Generated_Source\PSoC5\core_cm3_psoc5.h</v>
<v>.\Generated_Source\PSoC5\core_cm3.c</v>
<v>.\Generated_Source\PSoC5\core_cm3.h</v>
<v>.\Generated_Source\PSoC5\CyBootAsmGnu.s</v>
<v>.\Generated_Source\PSoC5\CyBootAsmRv.s</v>
<v>.\Generated_Source\PSoC5\CyDmac.c</v>
<v>.\Generated_Source\PSoC5\CyDmac.h</v>
<v>.\Generated_Source\PSoC5\CyFlash.c</v>
<v>.\Generated_Source\PSoC5\CyFlash.h</v>
<v>.\Generated_Source\PSoC5\CyLib.c</v>
<v>.\Generated_Source\PSoC5\CyLib.h</v>
<v>.\Generated_Source\PSoC5\cypins.h</v>
<v>.\Generated_Source\PSoC5\cyPm.c</v>
<v>.\Generated_Source\PSoC5\cyPm.h</v>
<v>.\Generated_Source\PSoC5\CySpc.c</v>
<v>.\Generated_Source\PSoC5\CySpc.h</v>
<v>.\Generated_Source\PSoC5\cytypes.h</v>
<v>.\Generated_Source\PSoC5\cyutils.c</v>
<v>.\Generated_Source\PSoC5\project.h</v>
<v>.\Generated_Source\PSoC5\PwmMotor.c</v>
<v>.\Generated_Source\PSoC5\PwmMotor.h</v>
<v>.\Generated_Source\PSoC5\PwmMotor_PM.c</v>
<v>.\Generated_Source\PSoC5\PIN_POT_aliases.h</v>
<v>.\Generated_Source\PSoC5\PIN_PWM_aliases.h</v>
<v>.\Generated_Source\PSoC5\PIN_PWM.c</v>
<v>.\Generated_Source\PSoC5\PIN_PWM.h</v>
<v>.\Generated_Source\PSoC5\Clock_1.c</v>
<v>.\Generated_Source\PSoC5\Clock_1.h</v>
<v>.\Generated_Source\PSoC5\ADC_SAR.c</v>
<v>.\Generated_Source\PSoC5\ADC_SAR.h</v>
<v>.\Generated_Source\PSoC5\ADC_SAR_INT.c</v>
<v>.\Generated_Source\PSoC5\ADC_SAR_PM.c</v>
<v>.\Generated_Source\PSoC5\PwmPiezo.c</v>
<v>.\Generated_Source\PSoC5\PwmPiezo.h</v>
<v>.\Generated_Source\PSoC5\PwmPiezo_PM.c</v>
<v>.\Generated_Source\PSoC5\Clock_2.c</v>
<v>.\Generated_Source\PSoC5\Clock_2.h</v>
<v>.\Generated_Source\PSoC5\PIN_PIEZO_PWM1_aliases.h</v>
<v>.\Generated_Source\PSoC5\PIN_PIEZO_PWM1.c</v>
<v>.\Generated_Source\PSoC5\PIN_PIEZO_PWM1.h</v>
<v>.\Generated_Source\PSoC5\PIN_PIEZO_PWM2_aliases.h</v>
<v>.\Generated_Source\PSoC5\PIN_PIEZO_PWM2.c</v>
<v>.\Generated_Source\PSoC5\PIN_PIEZO_PWM2.h</v>
<v>.\Generated_Source\PSoC5\PIN_MOTION_ALARM_aliases.h</v>
<v>.\Generated_Source\PSoC5\PIN_MOTION_ALARM.c</v>
<v>.\Generated_Source\PSoC5\PIN_MOTION_ALARM.h</v>
<v>.\Generated_Source\PSoC5\ISR_MOTION_ALARM.c</v>
<v>.\Generated_Source\PSoC5\ISR_MOTION_ALARM.h</v>
<v>.\Generated_Source\PSoC5\ADC_SAR_theACLK.c</v>
<v>.\Generated_Source\PSoC5\ADC_SAR_theACLK.h</v>
<v>.\Generated_Source\PSoC5\ADC_SAR_Bypass_aliases.h</v>
<v>.\Generated_Source\PSoC5\ADC_SAR_Bypass.c</v>
<v>.\Generated_Source\PSoC5\ADC_SAR_Bypass.h</v>
<v>.\Generated_Source\PSoC5\PinLedGreen_aliases.h</v>
<v>.\Generated_Source\PSoC5\PinLedGreen.c</v>
<v>.\Generated_Source\PSoC5\PinLedGreen.h</v>
<v>.\Generated_Source\PSoC5\PinLedOrange_aliases.h</v>
<v>.\Generated_Source\PSoC5\PinLedOrange.c</v>
<v>.\Generated_Source\PSoC5\PinLedOrange.h</v>
<v>.\Generated_Source\PSoC5\PinLedRed_aliases.h</v>
<v>.\Generated_Source\PSoC5\PinLedRed.c</v>
<v>.\Generated_Source\PSoC5\PinLedRed.h</v>
<v>.\Generated_Source\PSoC5\PinLightFrontLeft_aliases.h</v>
<v>.\Generated_Source\PSoC5\PinLightFrontLeft.c</v>
<v>.\Generated_Source\PSoC5\PinLightFrontLeft.h</v>
<v>.\Generated_Source\PSoC5\PinLightFrontRight_aliases.h</v>
<v>.\Generated_Source\PSoC5\PinLightFrontRight.c</v>
<v>.\Generated_Source\PSoC5\PinLightFrontRight.h</v>
<v>.\Generated_Source\PSoC5\PinLightRear_aliases.h</v>
<v>.\Generated_Source\PSoC5\PinLightRear.c</v>
<v>.\Generated_Source\PSoC5\PinLightRear.h</v>
<v>.\Generated_Source\PSoC5\PinLightSkirting_aliases.h</v>
<v>.\Generated_Source\PSoC5\PinLightSkirting.c</v>
<v>.\Generated_Source\PSoC5\PinLightSkirting.h</v>
<v>.\Generated_Source\PSoC5\UartXbee.c</v>
<v>.\Generated_Source\PSoC5\UartXbee.h</v>
<v>.\Generated_Source\PSoC5\UartXbee_PM.c</v>
<v>.\Generated_Source\PSoC5\UartXbee_INT.c</v>
<v>.\Generated_Source\PSoC5\PinXbeeSleep_aliases.h</v>
<v>.\Generated_Source\PSoC5\PinXbeeSleep.c</v>
<v>.\Generated_Source\PSoC5\PinXbeeSleep.h</v>
<v>.\Generated_Source\PSoC5\TimerMainTick.c</v>
<v>.\Generated_Source\PSoC5\TimerMainTick.h</v>
<v>.\Generated_Source\PSoC5\TimerMainTick_PM.c</v>
<v>.\Generated_Source\PSoC5\IsrMainTick.c</v>
<v>.\Generated_Source\PSoC5\IsrMainTick.h</v>
<v>.\Generated_Source\PSoC5\PinPwmMotor_aliases.h</v>
<v>.\Generated_Source\PSoC5\PinPwmMotor.c</v>
<v>.\Generated_Source\PSoC5\PinPwmMotor.h</v>
<v>.\Generated_Source\PSoC5\ClockPwmMotor.c</v>
<v>.\Generated_Source\PSoC5\ClockPwmMotor.h</v>
<v>.\Generated_Source\PSoC5\ClockPwmPiezo.c</v>
<v>.\Generated_Source\PSoC5\ClockPwmPiezo.h</v>
<v>.\Generated_Source\PSoC5\PinPwmPiezo_aliases.h</v>
<v>.\Generated_Source\PSoC5\PinPwmPiezo.c</v>
<v>.\Generated_Source\PSoC5\PinPwmPiezo.h</v>
<v>.\Generated_Source\PSoC5\PinMotionSensor_aliases.h</v>
<v>.\Generated_Source\PSoC5\PinMotionSensor.c</v>
<v>.\Generated_Source\PSoC5\PinMotionSensor.h</v>
<v>.\Generated_Source\PSoC5\IsrMotionSensor.c</v>
<v>.\Generated_Source\PSoC5\IsrMotionSensor.h</v>
<v>.\Generated_Source\PSoC5\UartDebug.c</v>
<v>.\Generated_Source\PSoC5\UartDebug.h</v>
<v>.\Generated_Source\PSoC5\UartDebug_PM.c</v>
<v>.\Generated_Source\PSoC5\UartDebug_INT.c</v>
<v>.\Generated_Source\PSoC5\PinLightFront_aliases.h</v>
<v>.\Generated_Source\PSoC5\PinLightFront.c</v>
<v>.\Generated_Source\PSoC5\PinLightFront.h</v>
<v>.\Generated_Source\PSoC5\ADC_SAR_1.c</v>
<v>.\Generated_Source\PSoC5\ADC_SAR_1.h</v>
<v>.\Generated_Source\PSoC5\ADC_SAR_1_INT.c</v>
<v>.\Generated_Source\PSoC5\ADC_SAR_1_PM.c</v>
<v>.\Generated_Source\PSoC5\ADC_SAR_1_theACLK.c</v>
<v>.\Generated_Source\PSoC5\ADC_SAR_1_theACLK.h</v>
<v>.\Generated_Source\PSoC5\AdcSar.c</v>
<v>.\Generated_Source\PSoC5\AdcSar.h</v>
<v>.\Generated_Source\PSoC5\AdcSar_INT.c</v>
<v>.\Generated_Source\PSoC5\AdcSar_PM.c</v>
<v>.\Generated_Source\PSoC5\AdcSar_theACLK.c</v>
<v>.\Generated_Source\PSoC5\AdcSar_theACLK.h</v>
</gen_list>
<warp_dep>
<v>C:\Program Files (x86)\Cypress\PSoC Creator\2.0\PSoC Creator\warp\lib\ieee\work\stdlogic.vif</v>
<v>C:\Program Files (x86)\Cypress\PSoC Creator\2.0\PSoC Creator\warp\lib\common\stdlogic\mod_genv.vif</v>
<v>C:\Program Files (x86)\Cypress\PSoC Creator\2.0\PSoC Creator\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\B_PWM_v2_10\B_PWM_v2_10.v</v>
<v>C:\Program Files (x86)\Cypress\PSoC Creator\2.0\PSoC Creator\warp\lib\common\cypress.v</v>
<v>C:\Program Files (x86)\Cypress\PSoC Creator\2.0\PSoC Creator\warp\lib\common\cy_psoc3_inc.v</v>
<v>C:\Program Files (x86)\Cypress\PSoC Creator\2.0\PSoC Creator\psoc\content\cyprimitives\CyPrimitives.cylib\cy_virtualmux_v1_0\cy_virtualmux_v1_0.v</v>
<v>C:\Program Files (x86)\Cypress\PSoC Creator\2.0\PSoC Creator\psoc\content\cyprimitives\CyPrimitives.cylib\OneTerminal\OneTerminal.v</v>
<v>C:\Program Files (x86)\Cypress\PSoC Creator\2.0\PSoC Creator\psoc\content\cyprimitives\CyPrimitives.cylib\ZeroTerminal\ZeroTerminal.v</v>
<v>C:\Program Files (x86)\Cypress\PSoC Creator\2.0\PSoC Creator\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\B_UART_v2_10\B_UART_v2_10.v</v>
<v>C:\Program Files (x86)\Cypress\PSoC Creator\2.0\PSoC Creator\psoc\content\cycomponentlibrary\CyComponentLibrary.cylib\B_Timer_v2_20\B_Timer_v2_20.v</v>
<v>C:\Program Files (x86)\Cypress\PSoC Creator\2.0\PSoC Creator\psoc\content\cyprimitives\CyPrimitives.cylib\cy_analog_virtualmux_v1_0\cy_analog_virtualmux_v1_0.v</v>
<v>C:\Program Files (x86)\Cypress\PSoC Creator\2.0\PSoC Creator\psoc\content\cyprimitives\CyPrimitives.cylib\cy_vref_v1_50\cy_vref_v1_50.v</v>
<v>C:\Program Files (x86)\Cypress\PSoC Creator\2.0\PSoC Creator\warp\lib\common\stdlogic\rtlpkg.vif</v>
<v>C:\Program Files (x86)\Cypress\PSoC Creator\2.0\PSoC Creator\warp\lib\common\stdlogic\cy_psoc3.vif</v>
</warp_dep>
<deps_time v="129839593539175460" />
</CyGuid_925cc1e1-309e-4e08-b0a1-09a83c35b157>
</dataGuid>
<dataGuid v="bf610382-39c6-441f-80b8-b04622ea7845">
<CyGuid_bf610382-39c6-441f-80b8-b04622ea7845 type_name="CyDesigner.Common.Debugger.CyWatchedVariableList" version="1">
<debugger_watch_list>
<CyGuid_ccf7a56e-c00d-460c-82dd-56c8f54feb7f type_name="CyDesigner.Common.Debugger.CyWatchedVariableList+CyWatchedItem" version="1" window="0" name="_commsTimeoutFlag" radix="Default" />
</debugger_watch_list>
</CyGuid_bf610382-39c6-441f-80b8-b04622ea7845>
</dataGuid>
</userData>
</CyGuid_fdba8dfd-b15b-4469-9bbb-9e40c3e70997>
<properties />
</CyGuid_7a7929f8-5e3b-4f86-a093-2d4ee6513111>
</CyXmlSerializer>