# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Geo\Documents\Projects\Electric Skateboard\Firmware\PSoC\Skateboard Remote.cydsn\Skateboard Remote.cyprj
# Date: Sat, 09 Jun 2012 04:48:13 GMT
#set_units -time ns
create_clock -name {ClockBlock/clk_bus} -period 41.666666666666664 -waveform {0 20.8333333333333} [get_pins {ClockBlock/clk_bus}]
create_clock -name {ClockBlock/dclk_0} -period 83.333333333333329 -waveform {0 41.6666666666667} [get_pins {ClockBlock/dclk_0}]
create_clock -name {ClockBlock/aclk_0} -period 541.66666666666663 -waveform {0 270.833333333333} [get_pins {ClockBlock/aclk_0}]
create_clock -name {ClockBlock/dclk_1} -period 2166.6666666666665 -waveform {0 1083.33333333333} [get_pins {ClockBlock/dclk_1}]
create_clock -name {ClockBlock/dclk_2} -period 13041.666666666666 -waveform {0 6520.83333333333} [get_pins {ClockBlock/dclk_2}]
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyXTAL} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/xtal}]]
create_generated_clock -name {CyIMO} -source [get_pins {ClockBlock/xtal}] -duty_cycle 50 [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyMASTER_CLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CapSense_IntClock} -source [get_pins {ClockBlock/clk_sync}] -divide_by 2 -duty_cycle 50 [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {AdcSar_theACLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 13 27} -nominal_period 541.66666666666663 [list [get_pins {ClockBlock/aclk_glb_0}]]
create_generated_clock -name {UartDebug_IntClock} -source [get_pins {ClockBlock/clk_sync}] -divide_by 52 -duty_cycle 50 -nominal_period 2166.6666666666665 [list [get_pins {ClockBlock/dclk_glb_1}]]
create_generated_clock -name {UartXbee_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 313 627} [list [get_pins {ClockBlock/dclk_glb_2}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -duty_cycle 50 [list [get_pins {ClockBlock/clk_bus_glb}]]

set_false_path -from [get_pins {__ONE__/q}]

# Component constraints for C:\Users\Geo\Documents\Projects\Electric Skateboard\Firmware\PSoC\Skateboard Remote.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Geo\Documents\Projects\Electric Skateboard\Firmware\PSoC\Skateboard Remote.cydsn\Skateboard Remote.cyprj
# Date: Sat, 09 Jun 2012 04:48:01 GMT
